#SMTP Configuration
#Thu May 07 12:01:09 WIB 2026
mail.sender.name=HR Metro
mail.smtp.auth=true
mail.smtp.host=mail.metroindonesia.com
mail.smtp.pass=Metr0mail\#2022
mail.smtp.port=587
mail.smtp.starttls.enable=true
mail.smtp.user=no-reply@metroindonesia.com
pdf.prefix=protected_
